name: Verilog

on:
  push:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Yosys
      run: sudo apt-get install yosys -y
    - name: Run yosys test
      run: yosys -p "hierarchy -check; proc;" ./pipeline/riscv.v
    - name: Run logic test
      run: ./testbench.sh
